name: Composite Action Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run composite action
        id: performance
        uses: ./.github/actions/hello-action
        with:
          environment: production
          threads: 100
          run_test: false

      - name: Show test result
        run: |
          echo "Test result from composite action: ${{ steps.performance.outputs.test-result }}"
